package lexer

type Token string

const (
	TokenEnd          Token = "$"
	TokenBracketOpen  Token = "("
	TokenBracketClose Token = ")"
)

var tokens = map[Token]struct{}{
	"id":     {},
	"number": {},
	"{":      {},
	"}":      {},
	"*":      {},
	"+":      {},
	"-":      {},
	"/":      {},
	"%":      {},
	"=":      {},
	"<":      {},
	"<=":     {},
	">=":     {},
	">":      {},
	"<>":     {},
	")":      {},
	"(":      {},
	"^":      {},
	";":      {},
}

func isToken(t string) bool {
	_, ok := tokens[Token(t)]
	return ok
}

type OpPrecedence string

const (
	OpPrecedenceUnknown OpPrecedence = ""
	OpPrecedenceLess    OpPrecedence = "<"
	OpPrecedenceMore    OpPrecedence = ">"
	OpPrecedenceEqual   OpPrecedence = "="
)

func OpTable(left, right Token) OpPrecedence {
	return opTable[left][right]
}

var opTable = map[Token]map[Token]OpPrecedence{
	"number": {
		"number": OpPrecedenceUnknown,
		"id":     OpPrecedenceUnknown,
		"^":      OpPrecedenceMore,
		"+":      OpPrecedenceMore,
		"-":      OpPrecedenceMore,
		"*":      OpPrecedenceMore,
		"/":      OpPrecedenceMore,
		"%":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"(":      OpPrecedenceUnknown,
		")":      OpPrecedenceMore,
		"$":      OpPrecedenceMore},
	"id": {
		"number": OpPrecedenceUnknown,
		"id":     OpPrecedenceUnknown,
		"^":      OpPrecedenceMore,
		"+":      OpPrecedenceMore,
		"-":      OpPrecedenceMore,
		"*":      OpPrecedenceMore,
		"/":      OpPrecedenceMore,
		"%":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"(":      OpPrecedenceUnknown,
		")":      OpPrecedenceMore,
		"$":      OpPrecedenceMore},
	"-": {
		"^":      OpPrecedenceLess,
		"id":     OpPrecedenceLess,
		"number": OpPrecedenceLess,
		"+":      OpPrecedenceMore,
		"%":      OpPrecedenceLess,
		"-":      OpPrecedenceMore,
		"*":      OpPrecedenceLess,
		"/":      OpPrecedenceLess,
		"(":      OpPrecedenceLess,
		")":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"$":      OpPrecedenceMore,
	},
	"+": {
		"^":      OpPrecedenceLess,
		"id":     OpPrecedenceLess,
		"number": OpPrecedenceLess,
		"+":      OpPrecedenceMore,
		"-":      OpPrecedenceMore,
		"*":      OpPrecedenceLess,
		"%":      OpPrecedenceLess,
		"/":      OpPrecedenceLess,
		"(":      OpPrecedenceLess,
		")":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"$":      OpPrecedenceMore,
	},
	"*": {
		"id":     OpPrecedenceLess,
		"number": OpPrecedenceLess,
		"+":      OpPrecedenceMore,
		"-":      OpPrecedenceMore,
		"^":      OpPrecedenceLess,
		"*":      OpPrecedenceMore,
		"/":      OpPrecedenceMore,
		"(":      OpPrecedenceLess,
		"%":      OpPrecedenceMore,
		")":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"$":      OpPrecedenceMore,
	},
	"%": {
		"number": OpPrecedenceLess,
		"id":     OpPrecedenceLess,
		"^":      OpPrecedenceLess,
		"+":      OpPrecedenceMore,
		"-":      OpPrecedenceMore,
		"*":      OpPrecedenceMore,
		"/":      OpPrecedenceMore,
		"%":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"(":      OpPrecedenceLess,
		")":      OpPrecedenceMore,
		"$":      OpPrecedenceMore},
	"^": {
		"number": OpPrecedenceLess,
		"id":     OpPrecedenceLess,
		"^":      OpPrecedenceMore,
		"+":      OpPrecedenceMore,
		"-":      OpPrecedenceMore,
		"*":      OpPrecedenceMore,
		"/":      OpPrecedenceMore,
		"%":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"(":      OpPrecedenceLess,
		")":      OpPrecedenceMore,
		"$":      OpPrecedenceMore},
	"/": {
		"id":     OpPrecedenceLess,
		"number": OpPrecedenceLess,
		"+":      OpPrecedenceMore,
		"^":      OpPrecedenceLess,
		"-":      OpPrecedenceMore,
		"*":      OpPrecedenceMore,
		"/":      OpPrecedenceMore,
		"(":      OpPrecedenceLess,
		")":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"%":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"$":      OpPrecedenceMore,
	},
	"<": {
		"id":     OpPrecedenceLess,
		"number": OpPrecedenceLess,
		"+":      OpPrecedenceLess,
		"-":      OpPrecedenceLess,
		"*":      OpPrecedenceLess,
		"/":      OpPrecedenceLess,
		"(":      OpPrecedenceLess,
		"%":      OpPrecedenceLess,
		"^":      OpPrecedenceLess,
		")":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"$":      OpPrecedenceMore,
	},
	"<=": {
		"id":     OpPrecedenceLess,
		"number": OpPrecedenceLess,
		"+":      OpPrecedenceLess,
		"^":      OpPrecedenceLess,
		"%":      OpPrecedenceLess,
		"-":      OpPrecedenceLess,
		"*":      OpPrecedenceLess,
		"/":      OpPrecedenceLess,
		"(":      OpPrecedenceLess,
		")":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"$":      OpPrecedenceMore,
	},
	">": {
		"id":     OpPrecedenceLess,
		"number": OpPrecedenceLess,
		"+":      OpPrecedenceLess,
		"-":      OpPrecedenceLess,
		"^":      OpPrecedenceLess,
		"%":      OpPrecedenceLess,
		"*":      OpPrecedenceLess,
		"/":      OpPrecedenceLess,
		"(":      OpPrecedenceLess,
		")":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"$":      OpPrecedenceMore,
	},
	">=": {
		"id":     OpPrecedenceLess,
		"number": OpPrecedenceLess,
		"+":      OpPrecedenceLess,
		"-":      OpPrecedenceLess,
		"*":      OpPrecedenceLess,
		"^":      OpPrecedenceLess,
		"%":      OpPrecedenceLess,
		"/":      OpPrecedenceLess,
		"(":      OpPrecedenceLess,
		")":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"$":      OpPrecedenceMore,
	},
	"=": {
		"id":     OpPrecedenceLess,
		"number": OpPrecedenceLess,
		"+":      OpPrecedenceLess,
		"^":      OpPrecedenceLess,
		"%":      OpPrecedenceLess,
		"-":      OpPrecedenceLess,
		"*":      OpPrecedenceLess,
		"/":      OpPrecedenceLess,
		"(":      OpPrecedenceLess,
		")":      OpPrecedenceMore,
		"<":      OpPrecedenceLess,
		"<=":     OpPrecedenceLess,
		">":      OpPrecedenceLess,
		">=":     OpPrecedenceLess,
		"=":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"$":      OpPrecedenceMore,
	},
	"<>": {
		"id":     OpPrecedenceLess,
		"number": OpPrecedenceLess,
		"+":      OpPrecedenceLess,
		"-":      OpPrecedenceLess,
		"*":      OpPrecedenceLess,
		"/":      OpPrecedenceLess,
		"(":      OpPrecedenceLess,
		")":      OpPrecedenceMore,
		"<":      OpPrecedenceLess,
		"<=":     OpPrecedenceLess,
		">":      OpPrecedenceLess,
		">=":     OpPrecedenceLess,
		"=":      OpPrecedenceMore,
		"^":      OpPrecedenceLess,
		"%":      OpPrecedenceLess,
		"<>":     OpPrecedenceMore,
		"$":      OpPrecedenceMore,
	},
	"(": {
		"id":     OpPrecedenceLess,
		"number": OpPrecedenceLess,
		"+":      OpPrecedenceLess,
		"-":      OpPrecedenceLess,
		"*":      OpPrecedenceLess,
		"/":      OpPrecedenceLess,
		"(":      OpPrecedenceLess,
		")":      OpPrecedenceEqual,
		"<":      OpPrecedenceLess,
		"<=":     OpPrecedenceLess,
		">":      OpPrecedenceLess,
		">=":     OpPrecedenceLess,
		"=":      OpPrecedenceLess,
		"<>":     OpPrecedenceLess,
		"^":      OpPrecedenceLess,
		"%":      OpPrecedenceLess,
		"$":      OpPrecedenceUnknown,
	},
	")": {
		"id":     OpPrecedenceUnknown,
		"number": OpPrecedenceUnknown,
		"+":      OpPrecedenceMore,
		"-":      OpPrecedenceMore,
		"*":      OpPrecedenceMore,
		"/":      OpPrecedenceMore,
		"(":      OpPrecedenceUnknown,
		")":      OpPrecedenceMore,
		"<":      OpPrecedenceMore,
		"<=":     OpPrecedenceMore,
		">":      OpPrecedenceMore,
		">=":     OpPrecedenceMore,
		"=":      OpPrecedenceMore,
		"<>":     OpPrecedenceMore,
		"^":      OpPrecedenceMore,
		"%":      OpPrecedenceMore,
		"$":      OpPrecedenceMore,
	},
	"$": {
		"id":     OpPrecedenceLess,
		"number": OpPrecedenceLess,
		"+":      OpPrecedenceLess,
		"-":      OpPrecedenceLess,
		"*":      OpPrecedenceLess,
		"/":      OpPrecedenceLess,
		"(":      OpPrecedenceLess,
		")":      OpPrecedenceUnknown,
		"<":      OpPrecedenceLess,
		"<=":     OpPrecedenceLess,
		">":      OpPrecedenceLess,
		">=":     OpPrecedenceLess,
		"=":      OpPrecedenceLess,
		"<>":     OpPrecedenceLess,
		"^":      OpPrecedenceLess,
		"%":      OpPrecedenceLess,
		"$":      OpPrecedenceUnknown,
	},
}
